<a href="https://colab.research.google.com/github/juanjosedelgado-coder/Talleres/blob/main/Taller_Importaci%C3%B3n_y_extraccion_de_datos_Marleny_Natalia_Juan_Cuaspud_Vargas_Delgado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Taller Importación y extraccion de datos**
#**Integrantes: Natalia Vargas, Juan Jose Delgado, Marleny Cuaspud**

##**Punto 1 base de paises del FMI (WEO) Desde drive**
Con este punto lastimosamente tuvimos un problema con la base de datos, ya que el Formato de Excel en el que éstas se encuentran es de una versión antigua la cual la librería panda no es capaz de trabajar Y a pesar De que intentamos De diversas formas e inclusive tratamos de trabajarlo por medio de visual Studio Code, Nos fue imposible por trabajar la base de datos y por ende no fuimos completar este punto. Sin embargo lo que sí pudimos hacer fue vincular el Google Colab Con el Google Drive que es donde se encuentra la base de datos.
Por este motivo nos gustaría solicitar Una red o la alimentación de su parte Sobre este punto para saber qué hacer cuando este tipo de situaciones se den y que en próximas oportunidades Podamos solucionarla.

In [ ]:
import pandas as pd

In [8]:
!pip install xlrd

Requirement already satisfied: xlrd in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [12]:
ruta = "/content/drive/MyDrive/Taller IA/weoapr2025all.xls"

In [9]:
ruta = "/content/drive/MyDrive/Taller IA/weoapr2025all.xls"

weo = pd.read_excel(ruta, engine="xlrd")

weo.head()

XLRDError: Unsupported format, or corrupt file: Expected BOF record; found b'W\x00E\x00O\x00 \x00'

##**Punto 2 API Colombia, Ecuador,Brasil, Chile, México y Perú**

In [17]:
!pip install wbdata
import wbdata
import pandas as pd
import datetime

Requirement already satisfied: wbdata in /usr/local/lib/python3.12/dist-packages (1.1.0)
Requirement already satisfied: appdirs<2,>=1.4 in /usr/local/lib/python3.12/dist-packages (from wbdata) (1.4.4)
Requirement already satisfied: backoff<3,>=2.2.1 in /usr/local/lib/python3.12/dist-packages (from wbdata) (2.2.1)
Requirement already satisfied: cachetools<6,>=5.3.2 in /usr/local/lib/python3.12/dist-packages (from wbdata) (5.5.2)
Requirement already satisfied: dateparser<2,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from wbdata) (1.3.0)
Requirement already satisfied: decorator<6,>=5.1.1 in /usr/local/lib/python3.12/dist-packages (from wbdata) (5.2.1)
Requirement already satisfied: requests<3,>=2.0 in /usr/local/lib/python3.12/dist-packages (from wbdata) (2.32.4)
Requirement already satisfied: shelved-cache<0.4,>=0.3.1 in /usr/local/lib/python3.12/dist-packages (from wbdata) (0.3.1)
Requirement already satisfied: tabulate<1,>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from wbdata) (0.9.0)
Requirement already satisfied: python-dateutil>=2.7.0 in /usr/local/lib/python3.12/dist-packages (from dateparser<2,>=1.2.0->wbdata) (2.9.0.post0)
Requirement already satisfied: pytz>=2024.2 in /usr/local/lib/python3.12/dist-packages (from dateparser<2,>=1.2.0->wbdata) (2025.2)
Requirement already satisfied: regex>=2024.9.11 in /usr/local/lib/python3.12/dist-packages (from dateparser<2,>=1.2.0->wbdata) (2025.11.3)
Requirement already satisfied: tzlocal>=0.2 in /usr/local/lib/python3.12/dist-packages (from dateparser<2,>=1.2.0->wbdata) (5.3.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0->wbdata) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0->wbdata) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0->wbdata) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0->wbdata) (2026.2.25)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7.0->dateparser<2,>=1.2.0->wbdata) (1.17.0)

In [18]:
paises = ["COL", "ECU", "BRA", "CHL", "MEX", "PER"]
indicador = {"FP.CPI.TOTL.ZG": "inflacion"}
inicio2 = datetime.datetime(2010, 1, 1)
fin2 = datetime.datetime(2023, 12, 31)
data = wbdata.get_dataframe(indicador, country=paises, date=(inicio2, fin2))
df = pd.DataFrame(data)
df.reset_index(inplace=True)
df.head() #Primeras 5 filas

  country  date  inflacion
0  Brazil  2023   4.593563
1  Brazil  2022   9.280106
2  Brazil  2021   8.301660
3  Brazil  2020   3.211768
4  Brazil  2019   3.732976

In [19]:
df.tail(10) #Ultimas 10 filas

   country  date  inflacion
74    Peru  2019   2.252122
75    Peru  2018   1.509154
76    Peru  2017   2.994900
77    Peru  2016   3.557177
78    Peru  2015   3.398092
79    Peru  2014   3.411946
80    Peru  2013   2.767897
81    Peru  2012   3.611213
82    Peru  2011   3.369311
83    Peru  2010   1.528321

In [42]:
df.sample(3) #filas aleatorias

   country  date  inflacion
62  Mexico  2017   6.041457
76    Peru  2017   2.994900
2   Brazil  2021   8.301660

In [45]:
df.iloc[1:5,1] # filas 2 a la 5, columna 2

1    2022
2    2021
3    2020
4    2019
Name: date, dtype: object

In [22]:
len(df) #numero de filas

84

In [23]:
df.shape #filas y columnas

(84, 3)

In [24]:
df.columns #columnas

Index(['country', 'date', 'inflacion'], dtype='object')

In [25]:
df.dtypes #tipos de datos

country       object
date          object
inflacion    float64
dtype: object

In [26]:
df.info #informacion completa

<bound method DataFrame.info of    country  date  inflacion
0   Brazil  2023   4.593563
1   Brazil  2022   9.280106
2   Brazil  2021   8.301660
3   Brazil  2020   3.211768
4   Brazil  2019   3.732976
..     ...   ...        ...
79    Peru  2014   3.411946
80    Peru  2013   2.767897
81    Peru  2012   3.611213
82    Peru  2011   3.369311
83    Peru  2010   1.528321

[84 rows x 3 columns]>

##**Punto 3 Alemania**

In [27]:
#Indicador = Código Banco Mundial
#PIB per cápita = NY.GDP.PCAP.CD
#Crecimiento del PIB	= NY.GDP.MKTP.KD.ZG
#Inflación	= FP.CPI.TOTL.ZG
#Desempleo = SL.UEM.TOTL.ZS
#Población total= SP.POP.TOTL
indicadores = {"NY.GDP.PCAP.CD": "pib_per_capita",
"NY.GDP.MKTP.KD.ZG": "crecimiento_pib",
"FP.CPI.TOTL.ZG": "inflacion",
"SL.UEM.TOTL.ZS": "desempleo",
"SP.POP.TOTL": "poblacion"}

In [28]:
pais = ["DEU"] #Codigo ISO del pais que usa el Banco Mundial para identificar países en su base de datos, alemania es "DEU"
inicio3 = datetime.datetime(2010, 1, 1)
fin3 = datetime.datetime(2023, 12, 31)

In [33]:
data_alemania = wbdata.get_dataframe(indicadores, country=pais, date=(inicio3, fin3))

In [34]:
df_alemania = pd.DataFrame(data_alemania)
df_alemania.reset_index(inplace=True)

In [35]:
df_alemania.head() #primeras 5 filas

   date  pib_per_capita  crecimiento_pib  inflacion  desempleo   poblacion
0  2023    54776.766824        -0.869648   5.946437      3.071  83287273.0
1  2022    50506.517964         1.809258   6.872574      3.137  83177813.0
2  2021    52349.245999         3.910000   3.066667      3.594  83196078.0
3  2020    47394.873450        -4.131914   0.144878      3.881  83160871.0
4  2019    47656.199740         0.977735   1.445660      3.163  83092962.0

In [37]:
df_alemania.tail(10) #ultimas 10 filas

    date  pib_per_capita  crecimiento_pib  inflacion  desempleo   poblacion
4   2019    47656.199740         0.977735   1.445660      3.163  83092962.0
5   2018    48916.168661         1.135696   1.732169      3.384  82905782.0
6   2017    45553.934150         2.797907   1.509495      3.781  82657002.0
7   2016    42948.938193         2.222222   0.491747      4.104  82348669.0
8   2015    41929.754911         1.663006   0.514426      4.612  81686611.0
9   2014    48959.599120         2.180186   0.906794      4.979  80982500.0
10  2013    47206.835351         0.396996   1.504723      5.316  80645605.0
11  2012    44718.015921         0.463512   2.008489      5.372  80425823.0
12  2011    47630.976188         3.757969   2.075173      5.967  80274983.0
13  2010    42396.966598         4.134638   1.103810      7.043  81776930.0

In [38]:
df_alemania.sample(3) #filas aleatorias

    date  pib_per_capita  crecimiento_pib  inflacion  desempleo   poblacion
5   2018    48916.168661         1.135696   1.732169      3.384  82905782.0
1   2022    50506.517964         1.809258   6.872574      3.137  83177813.0
10  2013    47206.835351         0.396996   1.504723      5.316  80645605.0

In [44]:
df_alemania.columns

Index(['date', 'pib_per_capita', 'crecimiento_pib', 'inflacion', 'desempleo',
       'poblacion'],
      dtype='object')

In [40]:
df_alemania.iloc[1:5,1] #filas 2 a 5 columna 2

1    1.809258
2    3.910000
3   -4.131914
4    0.977735
Name: crecimiento_pib, dtype: float64

In [46]:
len(df_alemania) #numero de filas

14

In [47]:
df_alemania.columns #columnas

Index(['date', 'pib_per_capita', 'crecimiento_pib', 'inflacion', 'desempleo',
       'poblacion'],
      dtype='object')

In [48]:
df_alemania.dtypes #tipos de datos

date                object
pib_per_capita     float64
crecimiento_pib    float64
inflacion          float64
desempleo          float64
poblacion          float64
dtype: object

In [51]:
df_alemania.info() #informacion

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             14 non-null     object
 1   pib_per_capita   14 non-null     float64
 2   crecimiento_pib  14 non-null     float64
 3   inflacion        14 non-null     float64
 4   desempleo        14 non-null     float64
 5   poblacion        14 non-null     float64
dtypes: float64(5), object(1)
memory usage: 804.0+ bytes

##**Punto 4 dos conjuntos**

In [53]:
import pandas as pd

df1 = pd.read_excel("/content/anex-IPC-ene2026.xlsx")

df1.head() #primeras 5 filas

                                          Unnamed: 0 Unnamed: 1 Unnamed: 2
0                                                NaN        NaN        NaN
1          PRODUCTO INTERNO BRUTO TRIMESTRAL (PIB_T)        NaN        NaN
2                                                NaN        NaN        NaN
3  Producto Interno Bruto desde el enfoque de la ...        NaN        NaN
4                                                NaN        NaN        NaN

In [54]:
df2 = pd.read_excel("/content/anex-ProduccionConstantes-IVtrim2025.xlsx")

df2.head()#primeras  5 filas

                                          Unnamed: 0 Unnamed: 1 Unnamed: 2
0                                                NaN        NaN        NaN
1          PRODUCTO INTERNO BRUTO TRIMESTRAL (PIB_T)        NaN        NaN
2                                                NaN        NaN        NaN
3  Producto Interno Bruto desde el enfoque de la ...        NaN        NaN
4                                                NaN        NaN        NaN

In [55]:
df1.tail(10) #utlimas 10 filas

   Unnamed: 0                                         Unnamed: 1
29        NaN                                                NaN
30        12.  Índice y variación mensual, año corrido y anua...
31        NaN                                                NaN
32        13.  Índice y variación mensual, año corrido y anua...
33        NaN                                                NaN
34        14.  Índice y variación mensual, año corrido y anua...
35        NaN                                                NaN
36        15.  Índice y variación mensual, año corrido y anua...
37        NaN                                                NaN
38        16.  Índice y variación mensual, año corrido y anua...

In [56]:
df1.sample(3) #filas aleatorias

   Unnamed: 0                                         Unnamed: 1
5         NaN                                                NaN
11        NaN                                                NaN
38        16.  Índice y variación mensual, año corrido y anua...

In [57]:
df1.iloc[1:5,1] #filas de 2 a 5, columna 2

1    NaN
2    NaN
3    NaN
4    NaN
Name: Unnamed: 1, dtype: object

In [58]:
df1.shape #numero de filas y columnas

(39, 2)

In [59]:
df1.columns #columnas

Index(['Unnamed: 0', 'Unnamed: 1'], dtype='object')

In [60]:
df1.dtypes #tipos de datos

Unnamed: 0    object
Unnamed: 1    object
dtype: object

In [61]:
df1.info() #informacion completa

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  19 non-null     object
 1   Unnamed: 1  16 non-null     object
dtypes: object(2)
memory usage: 756.0+ bytes

In [62]:
df2.tail(10) #utlimas 10 filas

,Unnamed: 0,Unnamed: 1,Unnamed: 2
4,NaN,NaN,NaN
5,NaN,NaN,NaN
6,NaN,Datos originales\n,NaN
7,NaN,Cuadro 1,12 agrupaciones - Secciones CIIU Rev. 4 A.C.
8,NaN,Cuadro 2,25 agrupaciones - Secciones CIIU Rev. 4 A.C.
9,NaN,Cuadro 3,61 agrupaciones - Secciones CIIU Rev. 4 A.C.
10,NaN,Datos ajustados por efecto estacional y calend...,NaN
11,NaN,Cuadro 4,12 agrupaciones - Secciones CIIU Rev. 4 A.C.
12,NaN,Cuadro 5,25 agrupaciones - Secciones CIIU Rev. 4 A.C.
13,NaN,Cuadro 6,61 agrupaciones - Secciones CIIU Rev. 4 A.C.

In [63]:
df2.sample(3) #filas aleatorias

,Unnamed: 0,Unnamed: 1,Unnamed: 2
5,NaN,NaN,NaN
10,NaN,Datos ajustados por efecto estacional y calend...,NaN
11,NaN,Cuadro 4,12 agrupaciones - Secciones CIIU Rev. 4 A.C.

In [64]:
df2.iloc[1:5,1] #filas de 2 a 5, columna 2

1    NaN
2    NaN
3    NaN
4    NaN
Name: Unnamed: 1, dtype: object

In [65]:
df2.shape #numero de filas y columnas

(14, 3)

In [66]:
df2.columns #columnas

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2'], dtype='object')

In [67]:
df2.dtypes #tipos de datos

Unnamed: 0    object
Unnamed: 1    object
Unnamed: 2    object
dtype: object

In [68]:
df2.info() #informacion completa

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  2 non-null      object
 1   Unnamed: 1  8 non-null      object
 2   Unnamed: 2  6 non-null      object
dtypes: object(3)
memory usage: 468.0+ bytes

##**Punto 5 otra pagina**

In [84]:
df_api = pd.read_excel("/content/anex-ProduccionConstantes-IVtrim2025.xlsx")

In [85]:
df_api.head() # primeras 5 filas

                                          Unnamed: 0 Unnamed: 1 Unnamed: 2
0                                                NaN        NaN        NaN
1          PRODUCTO INTERNO BRUTO TRIMESTRAL (PIB_T)        NaN        NaN
2                                                NaN        NaN        NaN
3  Producto Interno Bruto desde el enfoque de la ...        NaN        NaN
4                                                NaN        NaN        NaN

In [86]:
df_api.tail(10) # ultimas 10 filas

,Unnamed: 0,Unnamed: 1,Unnamed: 2
4,NaN,NaN,NaN
5,NaN,NaN,NaN
6,NaN,Datos originales\n,NaN
7,NaN,Cuadro 1,12 agrupaciones - Secciones CIIU Rev. 4 A.C.
8,NaN,Cuadro 2,25 agrupaciones - Secciones CIIU Rev. 4 A.C.
9,NaN,Cuadro 3,61 agrupaciones - Secciones CIIU Rev. 4 A.C.
10,NaN,Datos ajustados por efecto estacional y calend...,NaN
11,NaN,Cuadro 4,12 agrupaciones - Secciones CIIU Rev. 4 A.C.
12,NaN,Cuadro 5,25 agrupaciones - Secciones CIIU Rev. 4 A.C.
13,NaN,Cuadro 6,61 agrupaciones - Secciones CIIU Rev. 4 A.C.

In [87]:
df_api.sample(3) # filas aleatorias

   Unnamed: 0 Unnamed: 1                                    Unnamed: 2
9         NaN   Cuadro 3  61 agrupaciones - Secciones CIIU Rev. 4 A.C.
12        NaN   Cuadro 5  25 agrupaciones - Secciones CIIU Rev. 4 A.C.
8         NaN   Cuadro 2  25 agrupaciones - Secciones CIIU Rev. 4 A.C.

In [88]:
df_api.iloc[1:5,1] # fila 2 a 5, columna 2

1    NaN
2    NaN
3    NaN
4    NaN
Name: Unnamed: 1, dtype: object

In [89]:
len(df_api) # numero de filas

14

In [90]:
df_api.shape # numero de filas y columnas

(14, 3)

In [91]:
df_api.columns #columnas

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2'], dtype='object')

In [92]:
df_api.dtypes #tipos de datos

Unnamed: 0    object
Unnamed: 1    object
Unnamed: 2    object
dtype: object

In [93]:
df_api.info() #informacion completa

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  2 non-null      object
 1   Unnamed: 1  8 non-null      object
 2   Unnamed: 2  6 non-null      object
dtypes: object(3)
memory usage: 468.0+ bytes